#DESSA FUNKTIONER ÄR TESTADE OCH KLARA
DROP TABLE IF exists T_ACCOUNT ;

CREATE TABLE T_ACCOUNT  (
	USERNAME varchar(32) NOT NULL,
	ACC_ID integer auto_increment,
	PASSWRD varchar(32) NOT NULL,
	ACTIVE boolean NOT NULL default false,
	primary key(acc_id),
	unique key(username)
);


DROP TABLE IF exists T_USERINFO;

CREATE TABLE T_USERINFO	(
	ACC_ID 	integer		NOT NULL,
	FNAME 	varchar(32) NOT NULL,
	LNAME 	varchar(32) NOT NULL,
	STREET 	varchar(32) NOT NULL,
	ZIPCODE	varchar(32) NOT NULL,
	CITY	varchar(32) NOT NULL,
	PHONE	varchar(32)  NOT NULL,
	EMAIL	varchar(32)  NOT NULL,
	FOREIGN KEY (ACC_ID) references T_ACCOUNT(ACC_ID) on delete cascade
);


DROP TABLE IF exists T_TO_BE_VALIDATED ;

CREATE TABLE T_TO_BE_VALIDATED(
	ACC_ID integer NOT NULL,
	ENTRYDATE DATETIME NOT NULL,
	CONFIRMATION_CODE varchar(32) NOT NULL,
	PRIMARY KEY (CONFIRMATION_CODE),
	FOREIGN KEY (ACC_ID) references T_ACCOUNT(ACC_ID) on delete cascade
);


DROP TABLE IF exists T_RESET_PASSWORD;

CREATE TABLE T_RESET_PASSWORD(
	ACC_ID integer NOT NULL,
	ENTRYDATE DATETIME NOT NULL,
	CONFIRMATION_CODE varchar(32) NOT NULL,
	PRIMARY KEY (CONFIRMATION_CODE),
	FOREIGN KEY (ACC_ID) references T_ACCOUNT(ACC_ID) on delete cascade
);
