drop view if exists AccountBasestations;
create view AccountBasestations as 
	select T_BASESTATION.ACC_ID as USER_ID, T_BASESTATION_INFO.BASE_NAME AS BASESTATION_ID 
	from T_BASESTATION, T_BASESTATION_INFO 
	where T_BASESTATION.BS_ID = T_BASESTATION_INFO.BS_ID;
	
drop view if exists TimeoutInformation;
create view TimeoutInformation as
	select T_BASESTATION_INET_ADDR.INET_ADDR as INET_ADDR, T_BASESTATION_INET_ADDR.ENTRYTIME as ENTRYTIME, T_BASESTATION.BS_ID as BS_ID, T_USERINFO.EMAIL as EMAIL 
	from T_BASESTATION_INET_ADDR, T_BASESTATION, T_USERINFO
	where T_BASESTATION_INET_ADDR.BS_ID = T_BASESTATION.BS_ID and T_BASESTATION.ACC_ID = T_USERINFO.ACC_ID;
	
